/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { HelloWorldContract } from "./HelloWorld";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "HelloWorld"): HelloWorldContract;
    }
  }
}

export { HelloWorldContract, HelloWorldInstance } from "./HelloWorld";
